/**
 * @file config.ts
 * @date 2025-01-20
 * @purpose To define environment variables (ENV) and CSS selectors (SELECTORS) used throughout the test framework.
 *
 * @alterations
 * - 2025-01-20: Initial version for handling environment configuration and CSS selectors.
 * - 2025-01-20: Updated DEBUG parsing and added fallback for TIMEOUT value.
 *  Module requirements:
 *     npm install winston
 *     npm install playwright
 *     npm install winston-daily-rotate-file
 */

export const ENV = {
    BASE_URL: process.env.BASE_URL || "http://localhost:8080/",
    HEADLESS: process.env.HEADLESS === "true",
    TIMEOUT: process.env.TIMEOUT ? parseInt(process.env.TIMEOUT) : 5000,
    TEST_SUITE: 'suite02',
    TEST_DIR: '.',
    DEBUG: false,
};

export const SELECTORS = {
    LOGIN: {
        EMPLOYEE_NUMBER_INPUT: 'select[name="tabel"]',
        LOGIN_INPUT: 'select[name="initial"]',
        PASSWORD_INPUT: 'input[name="password"]',
        LOGIN_BUTTON: 'button[type="submit"]',
        ERROR_MESSAGE: ".alert.result.alert-danger",
    },

    MAINMENU: {
        PRODUCT: {
            URL: "product",
            TEXT_RUS: "продукция НПО Автомотив",
            TEXT_ENG: "Product",
            DATA_TESTID: "create-dataid", //changed for testing
            BREADCRUMB_SELECTOR: ".breadcrumb",
        },
        RESULTS: {
            URL: "resultwork",
            TEXT_RUS: "Результаты работы",
            TEXT_ENG: "Results",
            DATA_TESTID: "menu-results",
        },
        LIBRARY: {
            URL: "library",
            TEXT_RUS: "Библиотека",
            TEXT_ENG: "Library",
            DATA_TESTID: "menu-library",
        },
        TASKS: {
            URL: "issues",
            TEXT_RUS: "Задачи",
            TEXT_ENG: "Issues",
            DATA_TESTID: "menu-tasks",
        },
        ASSEMBLY_UNITS: {
            URL: "cbed",
            TEXT_RUS: "База сборочных единиц",
            TEXT_ENG: "Assembly Units",
            DATA_TESTID: "menu-assembly-units",
        },
        PARTS_DATABASE: {
            URL: "basedetals",
            TEXT_RUS: "База деталей",
            TEXT_ENG: "Parts",
            DATA_TESTID: "menu-parts",
        },
        MATERIALS: {
            URL: "basematerial",
            TEXT_RUS: "База материалов",
            TEXT_ENG: "Materials",
            DATA_TESTID: "menu-materials",
        },
        TOOLS: {
            URL: "basetools",
            TEXT_RUS: "База инструмента и оснастки",
            TEXT_ENG: "Tools",
            DATA_TESTID: "menu-tools",
        },
        EQUIPMENT: {
            URL: "baseequipment",
            TEXT_RUS: "База оборудования",
            TEXT_ENG: "Equipment",
            DATA_TESTID: "menu-equipment",
        },
        OPERATIONS: {
            URL: "inventary",
            TEXT_RUS: "База техники и инвентаря",
            TEXT_ENG: "Inventary",
            DATA_TESTID: "menu-operations",
        },
        SUPPLIERS: {
            URL: "baseprovider",
            TEXT_RUS: "База поставщиков",
            TEXT_ENG: "Suppliers",
            DATA_TESTID: "menu-suppliers",
        },
        BUYERS: {
            URL: "basebuyer",
            TEXT_RUS: "База покупателей",
            TEXT_ENG: "Customers",
            DATA_TESTID: "menu-buyers",
        },
        FILES: {
            URL: "filebase",
            TEXT_RUS: "База файлов",
            TEXT_ENG: "Files",
            DATA_TESTID: "menu-files",
        },
        SHIPPING_TASKS: {
            URL: "issueshipment",
            TEXT_RUS: "Задачи на отгрузку",
            TEXT_ENG: "Shipping Issues",
            DATA_TESTID: "menu-shipping-tasks",
        },
        WAREHOUSE: {
            URL: "sclad",
            TEXT_RUS: "Склад",
            TEXT_ENG: "Warehouse",
            DATA_TESTID: "MenuLeft-warehouse-read",
        },
        PRODUCTION: {
            URL: "production",
            TEXT_RUS: "Производство",
            TEXT_ENG: "Production",
            DATA_TESTID: "menu-production",
        },
        ACTIONS: {
            URL: "actions",
            TEXT_RUS: "Действия",
            TEXT_ENG: "Actions",
            DATA_TESTID: "menu-actions",
        },
        REJECT: {
            URL: "reject",
            TEXT_RUS: "Брак",
            TEXT_ENG: "Reject",
            DATA_TESTID: "menu-reject",
        },
        WASTE: {
            URL: "waste",
            TEXT_RUS: "Отходы",
            TEXT_ENG: "Waste",
            DATA_TESTID: "menu-waste",
        },
        WRITE_OFF: {
            URL: "write-off",
            TEXT_RUS: "Списание",
            TEXT_ENG: "Write Off",
            DATA_TESTID: "menu-write-off",
        },
        REPORTS: {
            URL: "reports",
            TEXT_RUS: "Отчеты",
            TEXT_ENG: "Reports",
            DATA_TESTID: "menu-reports",
        },
        COMPLAINT: {
            URL: "complaint",
            TEXT_RUS: "Рекламация",
            TEXT_ENG: "Complaint",
            DATA_TESTID: "menu-complaint",
        },
        ARCHIVE: {
            URL: "archive",
            TEXT_RUS: "Архив",
            TEXT_ENG: "Archive",
            DATA_TESTID: "menu-archive",
        },
    },
    SUBPAGES: {
        CREATEDETAIL: {
            URL: "detal/add",
            TEXT_RUS: "Создать деталь",
            TEXT_ENG: "Create Part",
            DATA_TESTID: "BaseDetals-Button-Create",
        },
    },


};
export const CONST = {
    PARTS_PAGE_RIGHT_TABLE_SEARCH_FIELD: "BasePaginationTable-Thead-SearchInput-Dropdown-Input",
    PARTS_PAGE_DETAL_TABLE: "BasePaginationTable-Table-detal",
    MAIN_PAGE_СБ_TABLE: "BasePaginationTable-Table-cbed",
    MAIN_SEARCH_COVER_INPUT: "OrderSuppliers-Main-Content-TableWrapper-Table-Search-Dropdown-Input",
    BASE_DETAIL_CB_TABLE_SEARCH: "BasePaginationTable-Thead-SearchInput-Dropdown-Input",
    EDIT_PARTS_PAGE_ARCHIVE_BUTTON: "EditDetal-ButtonSaveAndCancel-ButtonsRight-Archive",
    ARCHIVE_MODAL_CONFIRM_DIALOG: "ModalConfirm",
    ARCHIVE_MODAL_CONFIRM_DIALOG_YES_BUTTON: "ModalConfirm-Content-Buttons-Yes",
    BASE_DETALS_BUTTON_CREATE: "BaseDetals-Button-Create",
    BASE_DETALS_CREAT_LINK_TITLE_BASE_OF_ASSEMBLY_UNITS: "BaseDetals-CreatLink-Titlebase-of-assembly-units",
    CREATOR_INFORMATION_INPUT: "Creator-Information-Input-Input",
    EDITOR_TABLE_SPECIFICATION_CBED: "Editor-TableSpecification-Cbed",
    CREATOR_BUTTON_SAVE_AND_CANCEL_BUTTONS_CENTER_SAVE: "Creator-ButtonSaveAndCancel-ButtonsCenter-Save",
    CREATOR_BUTTON_SAVE_AND_CANCEL_BUTTONS_CENTER_CANCEL: "Creator-ButtonSaveAndCancel-ButtonsCenter-Cancel",
    ADD_DETAL_BUTTON_SAVE_AND_CANCEL_BUTTONS_CENTER_SAVE: "AddDetal-ButtonSaveAndCancel-ButtonsCenter-Save",
    EDIT_DETAL_BUTTON_SAVE_AND_CANCEL_BUTTONS_CENTER_CANCEL: "EditDetal-ButtonSaveAndCancel-ButtonsCenter-Cancel",
    MAIN_PAGE_EDIT_BUTTON: "BaseDetals-Button-Edit",

    ADD_DETAL_INFORMATION_INPUT_INPUT: "AddDetal-Information-Input-Input",
    EDIT_DETAL_INFORMATION_INPUT_INPUT: "EditDetal-Information-Input-Input",
    EDIT_DETAL_TITLE: "EditDetal-Title",
    CREATOR_TITLE: "Creator-Title",
    MODAL_TITLE: "OrderSuppliers-Modal-AddOrder-ModalAddStockOrderSupply-Main-Title",
    SCLAD_REVISION_REVISION: "Sclad-revision-revision",
    REVISION_SWITCH_ITEM2: "Revision-Switch-Item2",
    TABLE_REVISION_PAGINATION_SEARCH_INPUT: "TableRevisionPagination-SearchInput-Dropdown-Input",
    INPUT_NUMBER_INPUT: "InputNumber-Input",
    TABLE_REVISION_PAGINATION_CONFIRM_DIALOG: "TableRevisionPagination-ConfirmDialog",
    TABLE_REVISION_PAGINATION_CONFIRM_DIALOG_APPROVE: "TableRevisionPagination-ConfirmDialog-Approve",
    //MODAL_ADD_ORDER_SUPPLIERS_ORDER_CREATION_MODAL_CONTENT: "OrderSuppliers-Modal-AddOrder",
    MODAL_ADD_ORDER_SUPPLIER_ORDER_CREATION_MODAL_CONTENT: "OrderSuppliers-Modal-AddOrder",
    SELECT_TYPE_OBJECT_OPERATION_ASSEMBLIES: "OrderSuppliers-Modal-AddOrder-Content-AssembleCard",
    MODAL_ADD_ORDER_PRODUCTION_TABLE_TABLE_ROW_YOUR_QUANTITY_INPUT: "-TdQuantity-InputNumber-Input",
    MODAL_ADD_ORDER_PRODUCTION_TABLE_TABLE_ROW_YOUR_QUANTITY_INPUT_START: "OrderSuppliers-Modal-AddOrder-ModalAddStockOrderSupply-Main-Content-Block-ChoosedTable2-Row",
    MODAL_ADD_ORDER_PRODUCTION_TABLE_ORDER_BUTTON: "OrderSuppliers-Modal-AddOrder-ModalAddStockOrderSupply-Bottom-ButtonsCenter-Save",
    MODAL_ADD_ORDER_PRODUCTION_DIALOG_BUTTON: "OrderSuppliers-Modal-AddOrder-ModalAddStockOrderSupply-Main-Content-Block-Button",
    ORDER_SUPPLIERS_TABLE_ORDER_TABLE: "OrderSuppliers-Main-Content-TableWrapper-Table",
    ORDER_MODAL: "OrderSuppliers-Main-Content-TableWrapper-Table-Modal-Worker",
    COMPLEX_SBORKA_BY_PLAN: "CompletCbed-Content-Table-Table-SearchInput-Dropdown-Input",
    SCLAD_ORDERING_SUPPLIERS: "Sclad-orderingSuppliers",
    ORDER_SUPPLIERS_DIV_CREATE_ORDER_BUTTON: "OrderSuppliers-Main-Button",
    MODAL_ADD_WAYBILL_WAYBILL_DETAILS_OWN_QUANTITY_INPUT: "ModalAddWaybill-WaybillDetails-OwnQuantityInput-Input",
    MODAL_ADD_WAYBILL_WAYBILL_DETAILS_NAME_CELL: "ModalAddWaybill-WaybillDetails-NameCell",
    MODAL_ADD_WAYBILL_SHIPMENT_DETAILS_TABLE_TOTAL_QUANTITY_LABEL: "ModalAddWaybill-ShipmentDetailsTable-TotalQuantityLabel",
    MODAL_ADD_WAYBILL_CONTROL_BUTTONS_COMPLETE_SET_BUTTON: "ModalAddWaybill-ControlButtons-CompleteSetButton",
    TABLE_COMPLECT_TABLE_ROW_CELL: "CompletCbed-Content-Table-Table-TableRow",
    TABLE_COMPLECT_TABLE_ROW_CELL_NAME: "-Name",
    TABLE_COMPLECT_TABLE_ROW_CELL_DESIGNATION: "-Designation",
    SCLAD_COMPLETION_CBED_PLAN: "Sclad-completionCbedPlan",
    TABLE_REVISION_PAGINATION_TABLE: "Revision-TableRevisionPagination-Detals-Table",
    MODAL_ADD_ORDER_PRODUCTION_DIALOG: "OrderSuppliers-Modal-AddOrder-ModalAddStockOrderSupply",
    TABLE_MODAL_ADD_ORDER_PRODUCTION_TABLE: "OrderSuppliers-Modal-AddOrder-ModalAddStockOrderSupply-Main-Content-Block-TableWrapper-Table1",
    MODAL_ADD_ORDER_PRODUCTION_BOTTOM_TABLE: "OrderSuppliers-Modal-AddOrder-ModalAddStockOrderSupply-Main-Content-Block-ChoosedTable2",
    MODAL_ADD_ORDER_PRODUCTION_TABLE_SEARCH_INPUT: "OrderSuppliers-Modal-AddOrder-ModalAddStockOrderSupply-Main-Content-Block-TableWrapper-Table1-Search-Dropdown-Input",
    ORDER_MODAL_TABLE: "OrderSuppliers-Main-Content-TableWrapper-Table-Modal-Worker-Content-BlockTable-Table-TableStockOrderItems-Table",
    TABLE_COMPLECT_TABLE: "CompletCbed-Content-Table-Table",
    MODAL_ADD_WAYBILL_WAYBILL_DETAILS_RIGHT: "TableComplect-ModalAddWaybill",
    MODAL_ADD_WAYBILL_WAYBILL_DETAILS_REQUIRED_QUANTITY_CELL: "ModalAddWaybill-WaybillDetails-RequiredQuantityCell",
    MODAL_ADD_WAYBILL_WAYBILL_DETAILS_COLLECTED_QUANTITY_CELL: "ModalAddWaybill-WaybillDetails-CollectedQuantityCell",

    // Constants unique to ERP-969.spec.ts
    MODAL_CONFIRM_DIALOG: "ModalConfirm",
    MODAL_CONFIRM_DIALOG_YES_BUTTON: "ModalConfirm-Content-Buttons-Yes",
    PARTS_PAGE_ARCHIVE_BUTTON: "BaseDetals-Button-Archive",
    SEARCH_COVER_INPUT_2: "TableRevisionPagination-SearchInput-Dropdown-Input",
    COMPLETING_CBE_TITLE_ASSEMBLY_KITTING_ON_PLAN: "CompletCbed-Title",
    SPECIFICATION_BUTTONS_ADDING_SPECIFICATION: "Specification-Buttons-addingSpecification",
    SPECIFICATION_DIALOG_CARD_BASE_DETAIL_1: "Specification-Dialog-CardbaseDetail1",
    SPECIFICATION_MODAL_BASE_DETAL_SELECT_BUTTON: "Specification-ModalBaseDetal-Select-Button",
    SPECIFICATION_MODAL_BASE_DETAL_ADD_BUTTON: "Specification-ModalBaseDetal-Add-Button",
    MODAL_PROMPT_MINI_BUTTON_CONFIRM: "ModalPromptMini-Button-Confirm",
    OSTATTKPCBD_DETAIL_TABLE: "OstatkPCBD-Detal-Table",
    MODAL_START_PRODUCTION_ORDER_NUMBER_VALUE: "ModalStartProduction-OrderNumberValue",
    MODAL_ADD_WAYBILL_WAYBILL_DETAILS_HEADING: "ModalAddWaybill-WaybillDetails-Heading",
    MODAL_ADD_WAYBILL_WAYBILL_DETAILS_RIGHT_INNER: "ModalAddWaybill-WaybillDetails-Right",
    MODAL_ADD_WAYBILL_SHIPMENT_DETAILS_TABLE_TABLE: "ModalAddWaybill-ShipmentDetailsTable-Table",
    MODAL_ADD_WAYBILL_SHIPMENT_DETAILS_TABLE_SCLAD_SET_CHECKBOX_CELL: "ModalAddWaybill-ShipmentDetailsTable-ScladSetCheckboxCell",
    TABLE_COMPLECT_TABLE_ROW_CELL_ORDERED: "-Ordred",
    TABLE_COMPLECT_TABLE_ROW_CELL_OPERATIONS: "-Operations",
    TABLE_COMPLECT_TABLE_ROW_CELL_STATUS: "-Status",
    TABLE_COMPLECT_TABLE_ROW_CELL_COMPLETION_LEVEL: "-Readness",
    TABLE_COMPLECT_TABLE_ROW_CELL_COMPLETED: "-Complited",
    TABLE_COMPLECT_TABLE_ROW_CELL_REMAINING: "-Left",
    NOTIFICATION_NOTIFICATION_DESCRIPTION: "Notification-Notification-Description",
    MINI_NAVIGATION_POS_DATA2: "Revision-Switch-Item2",
    MODAL_ADD_WAYBILL_DETAILS_TABLE_ROW: "ModalAddWaybill-DetailsTable-Row",
    QUANTITY_PER_UNIT_CELL: "QuantityPerUnitCell",
    MATERIAL_CELL: "MaterialCell",
    NEED_CELL: "NeedCell",
    FREE_QUANTITY_CELL: "FreeQuantityCell",
    QUANTITY_CELL: "QuantityCell",
    IN_KITS_CELL: "InKitsCell",
    DEFICIT_CELL: "DeficitCell",
    OSTATTKPCBD_TABLE_SEARCH_INPUT: "OstatkiPCBDTable-SearchInput-Dropdown-Input",
    TABLE_REVISION_PAGINATION_EDIT_PEN: "InputNumber-Input",
    // Test Data
    SEARCH_TEXT: "NonExistentDetail",
    NEW_DETAIL_A: "0T5.21",  // For type Д (the main detail)
    NEW_SB_A: "0T5.11",      // For the new СБ detail
    DETAIL_1_NAME: "ERP9692_DETAIL_001",
    DETAIL_2_NAME: "ERP9692_DETAIL_002",
    ASSEMBLY_NAME: "ERP9692_ASSEMBLY_001",
    DETAIL_NEW_QUANTITY: "9",
    NEW_ORDER_QUANTITY: "3",

    // Constants unique to ERP-969-2.spec.ts
    SEARCH_COVER_INPUT: "Search-Cover-Input",
    MODAL_ADD_WAYBILL_SHIPMENT_DETAILS_TABLE_SCLAD_SET_SELECTED_CHECKBOX: "ModalAddWaybill-ShipmentDetailsTable-ScladSetSelectedCheckbox",
    MODAL_ADD_WAYBILL_SHIPMENT_DETAILS_TABLE_STOCK_ORDER_ROW_ORDER_NUMBER_CELL_PREFIX: "ModalAddWaybill-ShipmentDetailsTable-StockOrderRow",
    MODAL_ADD_WAYBILL_SHIPMENT_DETAILS_TABLE_STOCK_ORDER_ROW_ORDER_NUMBER_CELL_SUFFIX: "-OrderNumberCell",
    MODAL_ADD_WAYBILL_SHIPMENT_DETAILS_TABLE_STOCK_ORDER_ROW_REMAINING_QUANTITY_CELL_SUFFIX: "-RemainingQuantityCell",
    MODAL_ADD_WAYBILL_CONTROL_BUTTONS_ACTUALIZE_BUTTON: "ModalAddWaybill-ControlButtons-ActualizeButton",
    MODAL_ADD_WAYBILL_SHIPMENT_DETAILS_TABLE_TOTAL_LEFT_TO_DO_LABEL: "ModalAddWaybill-ShipmentDetailsTable-TotalLeftToDoLabel",
    MODAL_ADD_WAYBILL_DETAILS_TABLE_TABLE: "ModalAddWaybill-DetailsTable-Table",
    MODAL_ADD_WAYBILL_DETAILS_TABLE_ROW_NAME_CELL_PREFIX: "ModalAddWaybill-DetailsTable-Row",
    MODAL_ADD_WAYBILL_DETAILS_TABLE_ROW_NAME_CELL_SUFFIX: "-NameCell",
    MODAL_ADD_WAYBILL_DETAILS_TABLE_ROW_QUANTITY_CELL_SUFFIX: "-QuantityCell",
    MODAL_ADD_WAYBILL_DETAILS_TABLE_ROW_IN_KITS_CELL_SUFFIX: "-InKitsCell",
    MODAL_ADD_WAYBILL_DETAILS_TABLE_ROW_FREE_QUANTITY_CELL_SUFFIX: "-FreeQuantityCell",
    MODAL_ADD_WAYBILL_DETAILS_TABLE_ROW_SCLAD_NEED_CELL_SUFFIX: "-ScladNeedCell",
    MODAL_ADD_WAYBILL_DETAILS_TABLE_ROW_NEED_CELL_SUFFIX: "-NeedCell",
    TABLE_COMPLECT_TABLE_COMPLECT_MODAL_ADD_WAYBILL_CIRCLE_PROGRESS_WRAPPER_PREFIX: "TableComplect-ModalAddWaybill",
    TABLE_COMPLECT_TABLE_COMPLECT_MODAL_ADD_WAYBILL_CIRCLE_PROGRESS_WRAPPER_SUFFIX: "-CircleProgress-Wrapper",
    OSTATK_PCBD_MODAL_DETAL_PREFIX: "OstatkPCBD-ModalDetal",
    OSTATK_PCBD_MODAL_DETAL_INFORMATION_NAME_NAME_SUFFIX: "-InformationName-Name",
    OSTATK_PCBD_MODAL_DETAL_BUTTONS_SHOW_FULL_INFORMATION_BUTTON_SUFFIX: "-Buttons-ShowFullInformationButton",

    // Constants for U004 files
    MAIN_PAGE_TITLE_ID: "BaseDetals-Header-Title",
    MAIN_PAGE_MAIN_DIV: "BaseDetals-Container-MainContainer",
    MAIN_PAGE_ИЗДЕЛИЕ_TABLE: "BasePaginationTable-Table-product",
    MAIN_PAGE_Д_TABLE: "BasePaginationTable-Table-detal",
    MAIN_PAGE_SMALL_DIALOG: "Specification-DialogSpecification",
    MAIN_PAGE_SMALL_DIALOG_Д: "Specification-Dialog-CardbaseDetail1",
    MAIN_PAGE_SMALL_DIALOG_СБ: "Specification-Dialog-CardbaseOfAssemblyUnits0",
    MAIN_PAGE_SMALL_DIALOG_РМ: "Specification-Dialog-CardtheDatabaseOfMaterials3",
    MAIN_PAGE_SMALL_DIALOG_ПД: "Specification-Dialog-CardtheDatabaseOfMaterials2",
    RESET_СБ_1: "Опора (Траверса Т10А)СБ",
    RESET_СБ_2: "Балка траверсы СБ",
    RESET_СБ_3: "Упор подвижный (Траверса Т10А)СБ",
    RESET_Д_1: "Опора штока d45мм",
    RESET_ПД_1: "Гайка шестигранная DIN934 М12",
    RESET_ПД_2: "Болт с полной резьбой DIN933 М8х40",
    MAIN_PAGE_SAVE_BUTTON: "Creator-ButtonSaveAndCancel-ButtonsCenter-Save",
    EDIT_PAGE_MAIN_ID: "Creator",
    EDIT_PAGE_SPECIFICATIONS_TABLE: "Editor-TableSpecification-Product",
    EDIT_PAGE_ADD_BUTTON: "Specification-Buttons-addingSpecification",
    EDIT_PAGE_ADD_СБ_RIGHT_DIALOG: "Specification-ModalBaseCbed",
    EDIT_PAGE_ADD_СБ_RIGHT_DIALOG_ADDTOBOTTOM_BUTTON: "Specification-ModalBaseCbed-Select-Button",
    EDIT_PAGE_ADD_СБ_RIGHT_DIALOG_ADDTOMAIN_BUTTON: "Specification-ModalBaseCbed-Add-Button",
    EDIT_PAGE_ADD_СБ_RIGHT_DIALOG_CANCEL_BUTTON: "Specification-ModalBaseCbed-Cancel-Button",
    EDIT_PAGE_ADD_СБ_RIGHT_DIALOG_BOTTOM_TABLE: "Specification-ModalBaseCbed-Table",
    EDIT_PAGE_ADD_Д_RIGHT_DIALOG: "Specification-ModalBaseDetal",
    EDIT_PAGE_ADD_Д_RIGHT_DIALOG_ADDTOBOTTOM_BUTTON: "Specification-ModalBaseDetal-Select-Button",
    EDIT_PAGE_ADD_Д_RIGHT_DIALOG_ADDTOMAIN_BUTTON: "Specification-ModalBaseDetal-Add-Button",
    EDIT_PAGE_ADD_Д_RIGHT_DIALOG_CANCEL_BUTTON: "Specification-ModalBaseDetal-Cancel-Button",
    EDIT_PAGE_ADD_Д_RIGHT_DIALOG_DETAIL_TABLE: "BasePaginationTable-Table-detal",
    EDIT_PAGE_ADD_Д_RIGHT_DIALOG_BOTTOM_TABLE: "Specification-ModalBaseDetal-Table",
    EDIT_PAGE_ADD_ПД_RIGHT_DIALOG: "ModalBaseMaterial",
    EDIT_PAGE_ADD_ПД_RIGHT_DIALOG_ITEM_TABLE: "ModalBaseMaterial-TableList-Table-Item",
    EDIT_PAGE_ADD_ПД_RIGHT_DIALOG_BOTTOM_TABLE: "ModalBaseMaterial-Table",
    EDIT_PAGE_ADD_ПД_RIGHT_DIALOG_ADDTOBOTTOM_BUTTON: "ModalBaseMaterial-Select-Button",
    EDIT_PAGE_ADD_ПД_RIGHT_DIALOG_ADDTOMAIN_BUTTON: "ModalBaseMaterial-Add-Button",
    EDIT_PAGE_ADD_РМ_RIGHT_DIALOG: "ModalBaseMaterial",
    EDIT_PAGE_ADD_РМ_RIGHT_DIALOG_ITEM_TABLE: "ModalBaseMaterial-TableList-Table-Item",
    EDIT_PAGE_ADD_РМ_RIGHT_DIALOG_BOTTOM_TABLE: "ModalBaseMaterial-Table",
    EDIT_PAGE_ADD_РМ_RIGHT_DIALOG_ADDTOBOTTOM_BUTTON: "ModalBaseMaterial-Select-Button",
    EDIT_PAGE_ADD_РМ_RIGHT_DIALOG_ADDTOMAIN_BUTTON: "ModalBaseMaterial-Add-Button",
    CREATE_DETAIL_PAGE_SPECIFICATION_ADD_BUTTON: "Specification-Buttons-addingSpecification",
    CREATE_DETAIL_PAGE_SPECIFICATION_ADDFILEFROMBASE_BUTTON: "AddDetal-FileComponent-AddFileButton",
    CREATE_DETAIL_PAGE_SPECIFICATION_ADDFILEDRAGNDROP_BUTTON: "AddDetal-FileComponent-DragAndDrop-Wrapper",
    CREATE_DETAIL_PAGE_DETAIL_CHARACTERISTICS_TABLE: "AddDetal-Characteristic-Table",
    CREATE_DETAIL_PAGE_WORKPIECE_CHARACTERISTICS_TABLE: "",
    CREATE_DETAIL_PAGE_DETAIL_PARAMETERS_TABLE: "AddDetal-Detail-Parameters",
    CREATE_DETAIL_PAGE_ADDMATERIAL_DIALOG_ТИП_TABLE: "ModalBaseMaterial-TableList-Table-Type-Table",
    CREATE_DETAIL_PAGE_ADDMATERIAL_DIALOG_ПОДТИП_TABLE: "ModalBaseMaterial-TableList-Table-SubType-Table",
    CREATE_DETAIL_PAGE_ADDMATERIAL_DIALOG_ITEM_TABLE: "ModalBaseMaterial-TableList-Table-Item-Table",
    TEST_PRODUCT: 'Т15',
    TESTCASE_2_PRODUCT_1: 'Т15',
    EDIT_BUTTON: 'BaseDetals-Button-Edit',
    TEST_PRODUCT_СБ: 'Впускной крапан М12',
    TESTCASE_2_PRODUCT_СБ: 'Впускной крапан М12',
    TESTCASE_2_PRODUCT_Д: 'Грибок 15',
    TESTCASE_2_PRODUCT_ПД: 'Блок питания БП12Б-Д1-24',
    TESTCASE_2_PRODUCT_РМ: 'Рулон бумажных полотенец',
    TESTCASE_2_PRODUCT_ASSIGNEMENT: "TESTTESTTEST",

    // Constants for U005 files
    LEFT_DATA_TABLE: "BasePaginationTable-Table-product",
    TEST_DETAIL_NAME: "U005_test2_DETAILName",
    TEST_CATEGORY: "3D печать",
    TEST_MATERIAL: "09Г2С (Сталь)",
    TEST_NAME: "Круг Сталь 09Г2С Ø100мм",
    TEST_FILE: "87.02-05.01.00СБ Маслобак (ДГП15)СБ.jpg",
    MAIN_PAGE_CREATE_BUTTON: "BaseDetals-Button-Create",
    MAIN_PAGE_CREATE_DETAIL_LINK: "BaseDetals-CreateLink-base-detail",
    ADD_DETAIL_INFORMATION_INPUT: "AddDetal-Information-Input-Input",
    ADD_DETAIL_CHARACTERISTIC_BLANKS: "AddDetal-CharacteristicBlanks",
    ADD_DETAIL_CHARACTERISTIC_BLANKS_TBODY: "AddDetal-CharacteristicBlanks-Tbody",
    ADD_DETAIL_CHARACTERISTIC_BLANKS_SELECTED_MATERIAL_NAME_SET: "AddDetal-CharacteristicBlanks-SelectedMaterialName-Set",
    ADD_DETAIL_CHARACTERISTIC_BLANKS_SELECTED_MATERIAL_NAME_RESET: "AddDetal-CharacteristicBlanks-SelectedMaterialName-Reset",
    ADD_DETAIL_CHARACTERISTIC_BLANKS_TITLE: "AddDetal-CharacteristicBlanks-Title",
    ADD_DETAIL_BUTTON_SAVE_AND_CANCEL_BUTTONS_CENTER_SAVE: "AddDetal-ButtonSaveAndCancel-ButtonsCenter-Save",
    MODAL_BASE_MATERIAL_TABLE_LIST_SWITCH: "ModalBaseMaterial-TableList-Switch",
    MODAL_BASE_MATERIAL_TABLE_LIST_SWITCH_ITEM1: "ModalBaseMaterial-TableList-Switch-Item1",
    MODAL_BASE_MATERIAL_TABLE_LIST_TABLE_TYPE: "ModalBaseMaterial-TableList-Table-Type",
    MODAL_BASE_MATERIAL_TABLE_LIST_TABLE_TYPE_SEARCH_INPUT_DROPDOWN_INPUT: "ModalBaseMaterial-TableList-Table-Type-SearchInput-Dropdown-Input",
    MODAL_BASE_MATERIAL_TABLE_LIST_TABLE_SUB_TYPE: "ModalBaseMaterial-TableList-Table-SubType",
    MODAL_BASE_MATERIAL_TABLE_LIST_TABLE_SUB_TYPE_SEARCH_INPUT_DROPDOWN_INPUT: "ModalBaseMaterial-TableList-Table-SubType-SearchInput-Dropdown-Input",
    MODAL_BASE_MATERIAL_TABLE_LIST_TABLE_ITEM: "ModalBaseMaterial-TableList-Table-Item",
    MODAL_BASE_MATERIAL_TABLE_LIST_TABLE_ITEM_SEARCH_INPUT_DROPDOWN_INPUT: "ModalBaseMaterial-TableList-Table-Item-SearchInput-Dropdown-Input",
    MODAL_BASE_MATERIAL_ADD_BUTTON: "ModalBaseMaterial-Add-Button",
    ADD_DETAIL_FILE_COMPONENT_ADD_FILE_BUTTON: "AddDetal-FileComponent-AddFileButton",
    ADD_DETAIL_FILE_COMPONENT: "AddDetal-FileComponent",
    ADD_DETAIL_FILE_COMPONENT_DOCUMENT_TABLE_TABLE: "AddDetal-FileComponent-DocumentTable-Table",
    ADD_DETAIL_FILE_COMPONENT_DOCUMENT_TABLE_BUTTONS_BUTTON_PRINT: "AddDetal-FileComponent-DocumentTable-Buttons-ButtonPrint",
    ADD_DETAIL_FILE_COMPONENT_DOCUMENT_TABLE_BUTTONS_DELETE_DOC: "AddDetal-FileComponent-DocumentTable-Buttons-DeleteDoc",
    ADD_DETAIL_FILE_COMPONENT_MODAL_BASE_FILES: "AddDetal-FileComponent-ModalBaseFiles",
    ADD_DETAIL_FILE_COMPONENT_MODAL_BASE_FILES_FILE_WINDOW_SWITCH_ITEM0: "AddDetal-FileComponent-ModalBaseFiles-FileWindow-Switch-Item0",
    ADD_DETAIL_FILE_COMPONENT_MODAL_BASE_FILES_FILE_WINDOW_FILE_TABLE: "AddDetal-FileComponent-ModalBaseFiles-FileWindow-FileTable",
    ADD_DETAIL_FILE_COMPONENT_MODAL_BASE_FILES_FILE_WINDOW_FILE_TABLE_SEARCH_DROPDOWN_INPUT: "AddDetal-FileComponent-ModalBaseFiles-FileWindow-FileTable-Search-Dropdown-Input",
    ADD_DETAIL_FILE_COMPONENT_MODAL_BASE_FILES_FILE_WINDOW_FILE_TABLE_TABLE: "AddDetal-FileComponent-ModalBaseFiles-FileWindow-FileTable-Table",
    ADD_DETAIL_FILE_COMPONENT_MODAL_BASE_FILES_FILE_WINDOW_ADD_BUTTON: "AddDetal-FileComponent-ModalBaseFiles-FileWindow-AddButton",
    ADD_DETAIL_FILE_COMPONENT_MODAL_BASE_FILES_TABLE: "AddDetal-FileComponent-ModalBaseFiles-Table",
    ADD_DETAIL_FILE_COMPONENT_MODAL_BASE_FILES_FOOTER_BUTTONS_ADD_BUTTON: "AddDetal-FileComponent-ModalBaseFiles-FooterButtons-AddButton",
    ADD_DETAIL_FILE_COMPONENT_MODAL_BASE_FILES_FILE_WINDOW_DROPDOWN: "AddDetal-FileComponent-ModalBaseFiles-FileWindow-Dropdown",
    ADD_DETAIL_FILE_COMPONENT_MODAL_BASE_FILES_FILE_WINDOW_FILE_TABLE_TABLE_THEAD: "AddDetal-FileComponent-ModalBaseFiles-FileWindow-FileTable-Table-Thead",
    ADD_DETAIL_FILE_COMPONENT_DRAG_AND_DROP_MODAL_ADD_FILE_MODAL: "AddDetal-FileComponent-DragAndDrop-ModalAddFile-Modal",
    ADD_DETAIL_FILE_COMPONENT_DRAG_AND_DROP_MODAL_ADD_FILE_SECTION: "AddDetal-FileComponent-DragAndDrop-ModalAddFile-Section",
    ADD_DETAIL_FILE_COMPONENT_DRAG_AND_DROP_MODAL_ADD_FILE_FILE: "AddDetal-FileComponent-DragAndDrop-ModalAddFile-File",
    ADD_DETAIL_FILE_COMPONENT_DRAG_AND_DROP_MODAL_ADD_FILE_TEXTAREA_DESCRIPTION_TEXTAREA: "AddDetal-FileComponent-DragAndDrop-ModalAddFile-Textarea-Description-Textarea",
    ADD_DETAIL_FILE_COMPONENT_DRAG_AND_DROP_MODAL_ADD_FILE_CHECKBOX_MAIN: "AddDetal-FileComponent-DragAndDrop-ModalAddFile-Checkbox-Main",
    ADD_DETAIL_FILE_COMPONENT_DRAG_AND_DROP_MODAL_ADD_FILE_INPUT_NUMBER_VERSION_INPUT: "AddDetal-FileComponent-DragAndDrop-ModalAddFile-InputNumber-Version-Input",
    ADD_DETAIL_FILE_COMPONENT_DRAG_AND_DROP_MODAL_ADD_FILE_INPUT_FILE_NAME_INPUT: "AddDetal-FileComponent-DragAndDrop-ModalAddFile-Input-FileName-Input",
    ADD_DETAIL_FILE_COMPONENT_DRAG_AND_DROP_MODAL_ADD_FILE_BUTTON_UPLOAD: "AddDetal-FileComponent-DragAndDrop-ModalAddFile-Button-Upload",
    ADD_DETAIL_CHARACTERISTIC_BLANKS_BAN_DIALOG: "ModalConfirm",

    // Constants for U006 files
    ADD_DETAIL_PAGE: "AddDetal",
    ADD_DETAL_TITLE: "AddDetal-Title",
    SWITCH_MATERIAL_ITEM_2: "ModalBaseMaterial-TableList-Switch-Item2",
    DETAIL_NAME_INPUT_EDIT: "EditDetal-Information-Input-Input",
    EDIT_CHARACTERISTIC_BLANKS_CONTAINER: "EditDetal-CharacteristicBlanks",
    CHARACTERISTIC_BLANKS_MATERIAL_BUTTON: "AddDetal-CharacteristicBlanks-SelectedMaterialName-Set",
    CHARACTERISTIC_BLANKS_MATERIAL_RESET_BUTTON: "AddDetal-CharacteristicBlanks-SelectedMaterialName-Reset",
    EDIT_SAVE_BUTTON: "EditDetal-ButtonSaveAndCancel-ButtonsCenter-Save",
    MATERIAL_MODAL: "ModalBaseMaterial",
    MATERIAL_TABLE: "ModalBaseMaterial-TableList-Table-Item",
    MATERIAL_SEARCH_INPUT: "ModalBaseMaterial-TableList-Table-Item-SearchInput-Dropdown-Input",
    MATERIAL_ADD_BUTTON: "ModalBaseMaterial-Add-Button",
    MATERIAL_SWITCH_ITEM1: "ModalBaseMaterial-TableList-Switch-Item1",
    MATERIAL_CANCEL_BUTTON: "ModalBaseMaterial-Cancel-Button",
    FILE_COMPONENT: "AddDetal-FileComponent",
    FILE_ADD_BUTTON: "AddDetal-FileComponent-AddFileButton",
    FILE_DRAG_DROP_MODAL: "AddDetal-FileComponent-DragAndDrop-ModalAddFile-Modal",
    FILE_DRAG_DROP_SECTION: "AddDetal-FileComponent-DragAndDrop-ModalAddFile-Section",
    FILE_DRAG_DROP_FILE: "AddDetal-FileComponent-DragAndDrop-ModalAddFile-File",
    FILE_DESCRIPTION_TEXTAREA: "AddDetal-FileComponent-DragAndDrop-ModalAddFile-Textarea-Description-Textarea",
    FILE_MAIN_CHECKBOX: "AddDetal-FileComponent-DragAndDrop-ModalAddFile-Checkbox-Main",
    FILE_VERSION_INPUT: "AddDetal-FileComponent-DragAndDrop-ModalAddFile-InputNumber-Version-Input",
    FILE_NAME_INPUT: "AddDetal-FileComponent-DragAndDrop-ModalAddFile-Input-FileName-Input",
    FILE_UPLOAD_BUTTON: "AddDetal-FileComponent-DragAndDrop-ModalAddFile-Button-Upload",
    FILE_BASE_MODAL: "AddDetal-FileComponent-ModalBaseFiles",
    FILE_BASE_SWITCH_ITEM0: "AddDetal-FileComponent-ModalBaseFiles-FileWindow-Switch-Item0",
    FILE_BASE_TABLE: "AddDetal-FileComponent-ModalBaseFiles-FileWindow-FileTable",
    FILE_BASE_SEARCH_INPUT: "AddDetal-FileComponent-ModalBaseFiles-FileWindow-FileTable-Search-Dropdown-Input",
    FILE_BASE_TABLE_INNER: "AddDetal-FileComponent-ModalBaseFiles-FileWindow-FileTable-Table",
    FILE_BASE_ADD_BUTTON: "AddDetal-FileComponent-ModalBaseFiles-FileWindow-AddButton",
    FILE_BASE_BOTTOM_TABLE: "AddDetal-FileComponent-ModalBaseFiles-Table",
    FILE_BASE_FOOTER_ADD_BUTTON: "AddDetal-FileComponent-ModalBaseFiles-FooterButtons-AddButton",
    DOCUMENT_TABLE: "AddDetal-FileComponent-DocumentTable",
    DOCUMENT_TABLE_ROW: "AddDetal-FileComponent-DocumentTable-Tbody-TableRow",
    DOCUMENT_TABLE_CHECKBOX: "AddDetal-FileComponent-DocumentTable-Checkbox",
    DOCUMENT_TABLE_PRINT_BUTTON: "AddDetal-FileComponent-DocumentTable-Buttons-ButtonPrint",
    DOCUMENT_TABLE_DELETE_BUTTON: "AddDetal-FileComponent-DocumentTable-Buttons-DeleteDoc",
    DOCUMENT_TABLE_NAME_CELL: "AddDetal-FileComponent-DocumentTable-Tbody-Name",
    DOCUMENT_TABLE_SELECTOR: "AddDetal-FileComponent-DocumentTable-Table",
    SPECIAL_CHAR_NAME: "Деталь@#!$%^&*()_+",
    TEST_MATERIAL_NAME: "Шестигранник Сталь 40х S22",
    TEST_MATERIAL_NAME_2: "Войлок акустический 10мм",
    TEST_MATERIAL_NAME_2_ATTRIBUTE_COUNT: 3,
    CHR_TABLE: "AddDetal-CharacteristicBlanks-Table",
    EDIT_CHR_TABLE: "EditDetal-CharacteristicBlanks-Table",
    ADD_DETAIL_CHARACTERISTIC_BLANKS_INPUT_PATTERN: "AddDetal-CharacteristicBlanks-Tbody-InputNumber",
    CHARACTERISTIC_BLANKS_INPUT_SUFFIX: "-Input",
    EDIT_DETAIL_CHARACTERISTIC_BLANKS_INPUT_PATTERN: "EditDetal-CharacteristicBlanks-Tbody-InputNumber",
    MATERIAL_REMOVE_BUTTON: "EditDetal-CharacteristicBlanks-SelectedMaterialName-Reset",
    ADD_DETAILE_RESET_MATERIAL_BUTTON: "AddDetal-CharacteristicBlanks-SelectedMaterialName-Reset",
    DETAIL_MATERIAL_ADD_BUTTON: "AddDetal-CharacteristicBlanks-SelectedMaterialName-Set",
    DETAIL_TABLE: "BasePaginationTable-Table-detal",
    TABLE_SEARCH_INPUT: "BasePaginationTable-Thead-SearchInput-Dropdown-Input",
    DETAIL_NAME_INPUT: "AddDetal-Information-Input-Input",
    CHARACTERISTIC_BLANKS_CONTAINER: "AddDetal-CharacteristicBlanks",
    CHARACTERISTIC_BLANKS_TITLE: "AddDetal-CharacteristicBlanks-Title",
    SAVE_BUTTON: "AddDetal-ButtonSaveAndCancel-ButtonsCenter-Save",
    ARCHIVE_BUTTON: "BaseDetals-Button-Archive",
    CONFIRM_MODAL: "ModalConfirm",
    CONFIRM_YES_BUTTON: "ModalConfirm-Content-Buttons-Yes",
    SEARCH_DROPDOWN_INPUT: "Search-Dropdown-Input",
    ARCHIVE_BUTTON_GENERIC: "Button",
    MODAL_CONFIRM_GENERIC: "ModalConfirm",
    MODAL_CONFIRM_YES_BUTTON_GENERIC: "ModalConfirm-Content-Buttons-Yes",
    ADD_DETAIL_BUTTONS_TECH_PROCESS: "AddDetal-Buttons-TechProcess",
    ADD_DETAIL_BUTTONS_COST_PRICE: "AddDetal-Buttons-CostPrice",
    ADD_DETAIL_BUTTONS_ACCESSORY: "AddDetal-Buttons-Accessory",
    ADD_DETAIL_BUTTONS_CHANGE_HISTORY: "AddDetal-Buttons-ChangeHistory",
    // U005 Button Constants
    BASE_DETALS_BUTTON_EDIT: "BaseDetals-Button-Edit",
    BASE_DETALS_BUTTON_CREATE_COPY: "BaseDetals-Button-CreateCopy",
    BASE_DETALS_BUTTON_ARCHIVE: "BaseDetals-Button-Archive",
    BASE_DETALS_FILTER_COMPONENT_SORT_BY_ATTENTION: "BaseDetals-Filter-Component-SortByAttention",
    BASE_DETALS_FILTER_COMPONENT_SORT_BY_DATE: "BaseDetals-Filter-Component-SortByDate",
};
