/**
 * @file config.ts
 * @date 2025-01-20
 * @purpose To define environment variables (ENV) and CSS selectors (SELECTORS) used throughout the test framework.
 *
 * @alterations
 * - 2025-01-20: Initial version for handling environment configuration and CSS selectors.
 * - 2025-01-20: Updated DEBUG parsing and added fallback for TIMEOUT value.
 *  Module requirements:
 *     npm install winston
 *     npm install playwright
 *     npm install winston-daily-rotate-file
 */

export const ENV = {
    BASE_URL: process.env.BASE_URL || "http://localhost:8080/",
    HEADLESS: process.env.HEADLESS === "true",
    TIMEOUT: process.env.TIMEOUT ? parseInt(process.env.TIMEOUT) : 5000,
    TEST_SUITE: 'ERP_969',
    TEST_DIR: '.',
    DEBUG: false,
};

export const SELECTORS = {
    LOGIN: {
        EMPLOYEE_NUMBER_INPUT: 'select[name="tabel"]',
        LOGIN_INPUT: 'select[name="initial"]',
        PASSWORD_INPUT: 'input[name="password"]',
        LOGIN_BUTTON: 'button[type="submit"]',
        ERROR_MESSAGE: ".alert.result.alert-danger",
    },

    MAINMENU: {
        PRODUCT: {
            URL: "product",
            TEXT_RUS: "продукция НПО Автомотив",
            TEXT_ENG: "Product",
            DATA_TESTID: "create-dataid", //changed for testing
            BREADCRUMB_SELECTOR: ".breadcrumb",
        },
        RESULTS: {
            URL: "resultwork",
            TEXT_RUS: "Результаты работы",
            TEXT_ENG: "Results",
            DATA_TESTID: "menu-results",
        },
        LIBRARY: {
            URL: "library",
            TEXT_RUS: "Библиотека",
            TEXT_ENG: "Library",
            DATA_TESTID: "menu-library",
        },
        TASKS: {
            URL: "issues",
            TEXT_RUS: "Задачи",
            TEXT_ENG: "Issues",
            DATA_TESTID: "menu-tasks",
        },
        ASSEMBLY_UNITS: {
            URL: "cbed",
            TEXT_RUS: "База сборочных единиц",
            TEXT_ENG: "Assembly Units",
            DATA_TESTID: "menu-assembly-units",
        },
        PARTS_DATABASE: {
            URL: "basedetals",
            TEXT_RUS: "База деталей",
            TEXT_ENG: "Parts",
            DATA_TESTID: "menu-parts",
        },
        MATERIALS: {
            URL: "basematerial",
            TEXT_RUS: "База материалов",
            TEXT_ENG: "Materials",
            DATA_TESTID: "menu-materials",
        },
        TOOLS: {
            URL: "basetools",
            TEXT_RUS: "База инструмента и оснастки",
            TEXT_ENG: "Tools",
            DATA_TESTID: "menu-tools",
        },
        EQUIPMENT: {
            URL: "baseequipment",
            TEXT_RUS: "База оборудования",
            TEXT_ENG: "Equipment",
            DATA_TESTID: "menu-equipment",
        },
        OPERATIONS: {
            URL: "inventary",
            TEXT_RUS: "База техники и инвентаря",
            TEXT_ENG: "Inventary",
            DATA_TESTID: "menu-operations",
        },
        SUPPLIERS: {
            URL: "baseprovider",
            TEXT_RUS: "База поставщиков",
            TEXT_ENG: "Suppliers",
            DATA_TESTID: "menu-suppliers",
        },
        BUYERS: {
            URL: "basebuyer",
            TEXT_RUS: "База покупателей",
            TEXT_ENG: "Customers",
            DATA_TESTID: "menu-buyers",
        },
        FILES: {
            URL: "filebase",
            TEXT_RUS: "База файлов",
            TEXT_ENG: "Files",
            DATA_TESTID: "menu-files",
        },
        SHIPPING_TASKS: {
            URL: "issueshipment",
            TEXT_RUS: "Задачи на отгрузку",
            TEXT_ENG: "Shipping Issues",
            DATA_TESTID: "menu-shipping-tasks",
        },
        WAREHOUSE: {
            URL: "sclad",
            TEXT_RUS: "Склад",
            TEXT_ENG: "Warehouse",
            DATA_TESTID: "MenuLeft-warehouse-read",
        },
        PRODUCTION: {
            URL: "production",
            TEXT_RUS: "Производство",
            TEXT_ENG: "Production",
            DATA_TESTID: "menu-production",
        },
        ACTIONS: {
            URL: "actions",
            TEXT_RUS: "Действия",
            TEXT_ENG: "Actions",
            DATA_TESTID: "menu-actions",
        },
        REJECT: {
            URL: "reject",
            TEXT_RUS: "Брак",
            TEXT_ENG: "Reject",
            DATA_TESTID: "menu-reject",
        },
        WASTE: {
            URL: "waste",
            TEXT_RUS: "Отходы",
            TEXT_ENG: "Waste",
            DATA_TESTID: "menu-waste",
        },
        WRITE_OFF: {
            URL: "write-off",
            TEXT_RUS: "Списание",
            TEXT_ENG: "Write Off",
            DATA_TESTID: "menu-write-off",
        },
        REPORTS: {
            URL: "reports",
            TEXT_RUS: "Отчеты",
            TEXT_ENG: "Reports",
            DATA_TESTID: "menu-reports",
        },
        COMPLAINT: {
            URL: "complaint",
            TEXT_RUS: "Рекламация",
            TEXT_ENG: "Complaint",
            DATA_TESTID: "menu-complaint",
        },
        ARCHIVE: {
            URL: "archive",
            TEXT_RUS: "Архив",
            TEXT_ENG: "Archive",
            DATA_TESTID: "menu-archive",
        },
    },
    SUBPAGES: {
        CREATEDETAIL: {
            URL: "detal/add",
            TEXT_RUS: "Создать деталь",
            TEXT_ENG: "Create Part",
            DATA_TESTID: "BaseDetals-Button-Create",
        },
    },


};
export const CONST = {
    PARTS_PAGE_RIGHT_TABLE_SEARCH_FIELD: "BasePaginationTable-Thead-SearchInput-Dropdown-Input",
    PARTS_PAGE_DETAL_TABLE: "BasePaginationTable-Table-detal",
    MAIN_PAGE_СБ_TABLE: "BasePaginationTable-Table-cbed",
    MAIN_SEARCH_COVER_INPUT: "OrderSuppliers-Main-Content-TableWrapper-Table-Search-Dropdown-Input",
    BASE_DETAIL_CB_TABLE_SEARCH: "BasePaginationTable-Thead-SearchInput-Dropdown-Input",
    EDIT_PARTS_PAGE_ARCHIVE_BUTTON: "EditDetal-ButtonSaveAndCancel-ButtonsRight-Archive",
    ARCHIVE_MODAL_CONFIRM_DIALOG: "ModalConfirm",
    ARCHIVE_MODAL_CONFIRM_DIALOG_YES_BUTTON: "ModalConfirm-Content-Buttons-Yes",
    BASE_DETALS_BUTTON_CREATE: "BaseDetals-Button-Create",
    BASE_DETALS_CREAT_LINK_TITLE_BASE_OF_ASSEMBLY_UNITS: "BaseDetals-CreatLink-Titlebase-of-assembly-units",
    CREATOR_INFORMATION_INPUT: "Creator-Information-Input-Input",
    EDITOR_TABLE_SPECIFICATION_CBED: "Editor-TableSpecification-Cbed",
    CREATOR_BUTTON_SAVE_AND_CANCEL_BUTTONS_CENTER_SAVE: "Creator-ButtonSaveAndCancel-ButtonsCenter-Save",
    CREATOR_BUTTON_SAVE_AND_CANCEL_BUTTONS_CENTER_CANCEL: "Creator-ButtonSaveAndCancel-ButtonsCenter-Cancel",
    ADD_DETAL_BUTTON_SAVE_AND_CANCEL_BUTTONS_CENTER_SAVE: "AddDetal-ButtonSaveAndCancel-ButtonsCenter-Save",
    EDIT_DETAL_BUTTON_SAVE_AND_CANCEL_BUTTONS_CENTER_CANCEL: "EditDetal-ButtonSaveAndCancel-ButtonsCenter-Cancel",
    MAIN_PAGE_EDIT_BUTTON: "BaseDetals-Button-Edit",

    ADD_DETAL_INFORMATION_INPUT_INPUT: "AddDetal-Information-Input-Input",
    EDIT_DETAL_INFORMATION_INPUT_INPUT: "EditDetal-Information-Input-Input",
    EDIT_DETAL_TITLE: "EditDetal-Title",
    CREATOR_TITLE: "Creator-Title",
    MODAL_TITLE: "OrderSuppliers-Modal-AddOrder-ModalAddStockOrderSupply-Main-Title",
    SCLAD_REVISION_REVISION: "Sclad-revision-revision",
    REVISION_SWITCH_ITEM2: "Revision-Switch-Item2",
    TABLE_REVISION_PAGINATION_SEARCH_INPUT: "TableRevisionPagination-SearchInput-Dropdown-Input",
    INPUT_NUMBER_INPUT: "InputNumber-Input",
    TABLE_REVISION_PAGINATION_CONFIRM_DIALOG: "TableRevisionPagination-ConfirmDialog",
    TABLE_REVISION_PAGINATION_CONFIRM_DIALOG_APPROVE: "TableRevisionPagination-ConfirmDialog-Approve",
    MODAL_ADD_ORDER_SUPPLIER_ORDER_CREATION_MODAL_CONTENT: "OrderSuppliers-Modal-AddOrder",
    SELECT_TYPE_OBJECT_OPERATION_ASSEMBLIES: "OrderSuppliers-Modal-AddOrder-Content-AssembleCard",
    MODAL_ADD_ORDER_PRODUCTION_TABLE_TABLE_ROW_YOUR_QUANTITY_INPUT: "-TdQuantity-InputNumber-Input",
    MODAL_ADD_ORDER_PRODUCTION_TABLE_TABLE_ROW_YOUR_QUANTITY_INPUT_START: "OrderSuppliers-Modal-AddOrder-ModalAddStockOrderSupply-Main-Content-Block-ChoosedTable2-Row",
    MODAL_ADD_ORDER_PRODUCTION_TABLE_ORDER_BUTTON: "OrderSuppliers-Modal-AddOrder-ModalAddStockOrderSupply-Bottom-ButtonsCenter-Save",
    MODAL_ADD_ORDER_PRODUCTION_DIALOG_BUTTON: "OrderSuppliers-Modal-AddOrder-ModalAddStockOrderSupply-Main-Content-Block-Button",
    ORDER_SUPPLIERS_TABLE_ORDER_TABLE: "OrderSuppliers-Main-Content-TableWrapper-Table",
    ORDER_MODAL: "OrderSuppliers-Main-Content-TableWrapper-Table-Modal-Worker",
    COMPLEX_SBORKA_BY_PLAN: "CompletCbed-Content-Table-Table-SearchInput-Dropdown-Input",
    SCLAD_ORDERING_SUPPLIERS: "Sclad-orderingSuppliers",
    ORDER_SUPPLIERS_DIV_CREATE_ORDER_BUTTON: "OrderSuppliers-Main-Button",
    MODAL_ADD_WAYBILL_WAYBILL_DETAILS_OWN_QUANTITY_INPUT: "ModalAddWaybill-WaybillDetails-OwnQuantityInput-Input",
    MODAL_ADD_WAYBILL_WAYBILL_DETAILS_NAME_CELL: "ModalAddWaybill-WaybillDetails-NameCell",
    MODAL_ADD_WAYBILL_SHIPMENT_DETAILS_TABLE_TOTAL_QUANTITY_LABEL: "ModalAddWaybill-ShipmentDetailsTable-TotalQuantityLabel",
    MODAL_ADD_WAYBILL_CONTROL_BUTTONS_COMPLETE_SET_BUTTON: "ModalAddWaybill-ControlButtons-CompleteSetButton",
    TABLE_COMPLECT_TABLE_ROW_CELL: "CompletCbed-Content-Table-Table-TableRow",
    TABLE_COMPLECT_TABLE_ROW_CELL_NAME: "-Name",
    TABLE_COMPLECT_TABLE_ROW_CELL_DESIGNATION: "-Designation",
    SCLAD_COMPLETION_CBED_PLAN: "Sclad-completionCbedPlan",
    TABLE_REVISION_PAGINATION_TABLE: "Revision-TableRevisionPagination-Detals-Table",
    MODAL_ADD_ORDER_PRODUCTION_DIALOG: "OrderSuppliers-Modal-AddOrder-ModalAddStockOrderSupply",
    TABLE_MODAL_ADD_ORDER_PRODUCTION_TABLE: "OrderSuppliers-Modal-AddOrder-ModalAddStockOrderSupply-Main-Content-Block-TableWrapper-Table1",
    MODAL_ADD_ORDER_PRODUCTION_BOTTOM_TABLE: "OrderSuppliers-Modal-AddOrder-ModalAddStockOrderSupply-Main-Content-Block-ChoosedTable2",
    MODAL_ADD_ORDER_PRODUCTION_TABLE_SEARCH_INPUT: "OrderSuppliers-Modal-AddOrder-ModalAddStockOrderSupply-Main-Content-Block-TableWrapper-Table1-Search-Dropdown-Input",
    ORDER_MODAL_TABLE: "OrderSuppliers-Main-Content-TableWrapper-Table-Modal-Worker-Content-BlockTable-Table-TableStockOrderItems-Table",
    TABLE_COMPLECT_TABLE: "CompletCbed-Content-Table-Table",
    MODAL_ADD_WAYBILL_WAYBILL_DETAILS_RIGHT: "TableComplect-ModalAddWaybill",
    MODAL_ADD_WAYBILL_WAYBILL_DETAILS_REQUIRED_QUANTITY_CELL: "ModalAddWaybill-WaybillDetails-RequiredQuantityCell",
    MODAL_ADD_WAYBILL_WAYBILL_DETAILS_COLLECTED_QUANTITY_CELL: "ModalAddWaybill-WaybillDetails-CollectedQuantityCell",

    // Constants unique to ERP-969.spec.ts
    MODAL_CONFIRM_DIALOG: "ModalConfirm",
    MODAL_CONFIRM_DIALOG_YES_BUTTON: "ModalConfirm-Content-Buttons-Yes",
    PARTS_PAGE_ARCHIVE_BUTTON: "BaseDetals-Button-Archive",
    SEARCH_COVER_INPUT_2: "TableRevisionPagination-SearchInput-Dropdown-Input",
    COMPLETING_CBE_TITLE_ASSEMBLY_KITTING_ON_PLAN: "CompletCbed-Title",
    SPECIFICATION_BUTTONS_ADDING_SPECIFICATION: "Specification-Buttons-addingSpecification",
    SPECIFICATION_DIALOG_CARD_BASE_DETAIL_1: "Specification-Dialog-CardbaseDetail1",
    SPECIFICATION_MODAL_BASE_DETAL_SELECT_BUTTON: "Specification-ModalBaseDetal-Select-Button",
    SPECIFICATION_MODAL_BASE_DETAL_ADD_BUTTON: "Specification-ModalBaseDetal-Add-Button",
    MODAL_PROMPT_MINI_BUTTON_CONFIRM: "ModalPromptMini-Button-Confirm",
    OSTATTKPCBD_DETAIL_TABLE: "OstatkPCBD-Detal-Table",
    MODAL_START_PRODUCTION_ORDER_NUMBER_VALUE: "ModalStartProduction-OrderNumberValue",
    MODAL_ADD_WAYBILL_WAYBILL_DETAILS_HEADING: "ModalAddWaybill-WaybillDetails-Heading",
    MODAL_ADD_WAYBILL_WAYBILL_DETAILS_RIGHT_INNER: "ModalAddWaybill-WaybillDetails-Right",
    MODAL_ADD_WAYBILL_SHIPMENT_DETAILS_TABLE_TABLE: "ModalAddWaybill-ShipmentDetailsTable-Table",
    MODAL_ADD_WAYBILL_SHIPMENT_DETAILS_TABLE_SCLAD_SET_CHECKBOX_CELL: "ModalAddWaybill-ShipmentDetailsTable-ScladSetCheckboxCell",
    TABLE_COMPLECT_TABLE_ROW_CELL_ORDERED: "-Ordred",
    TABLE_COMPLECT_TABLE_ROW_CELL_OPERATIONS: "-Operations",
    TABLE_COMPLECT_TABLE_ROW_CELL_STATUS: "-Status",
    TABLE_COMPLECT_TABLE_ROW_CELL_COMPLETION_LEVEL: "-Readness",
    TABLE_COMPLECT_TABLE_ROW_CELL_COMPLETED: "-Complited",
    TABLE_COMPLECT_TABLE_ROW_CELL_REMAINING: "-Left",
    NOTIFICATION_NOTIFICATION_DESCRIPTION: "Notification-Notification-Description",
    MINI_NAVIGATION_POS_DATA2: "Revision-Switch-Item2",
    MODAL_ADD_WAYBILL_DETAILS_TABLE_ROW: "ModalAddWaybill-DetailsTable-Row",
    QUANTITY_PER_UNIT_CELL: "QuantityPerUnitCell",
    MATERIAL_CELL: "MaterialCell",
    NEED_CELL: "NeedCell",
    FREE_QUANTITY_CELL: "FreeQuantityCell",
    QUANTITY_CELL: "QuantityCell",
    IN_KITS_CELL: "InKitsCell",
    DEFICIT_CELL: "DeficitCell",
    OSTATTKPCBD_TABLE_SEARCH_INPUT: "OstatkiPCBDTable-SearchInput-Dropdown-Input",
    TABLE_REVISION_PAGINATION_EDIT_PEN: "InputNumber-Input",
    // Test Data
    SEARCH_TEXT: "NonExistentDetail",
    NEW_DETAIL_A: "0T5.21",  // For type Д (the main detail)
    NEW_SB_A: "0T5.11",      // For the new СБ detail
    DETAIL_1_NAME: "ERP9692_DETAIL_001",
    DETAIL_2_NAME: "ERP9692_DETAIL_002",
    ASSEMBLY_NAME: "ERP9692_ASSEMBLY_001",
    DETAIL_NEW_QUANTITY: "9",
    NEW_ORDER_QUANTITY: "3",

    // Constants unique to ERP-969-2.spec.ts
    SEARCH_COVER_INPUT: "Search-Cover-Input",
    MODAL_ADD_WAYBILL_SHIPMENT_DETAILS_TABLE_SCLAD_SET_SELECTED_CHECKBOX: "ModalAddWaybill-ShipmentDetailsTable-ScladSetSelectedCheckbox",
    MODAL_ADD_WAYBILL_SHIPMENT_DETAILS_TABLE_STOCK_ORDER_ROW_ORDER_NUMBER_CELL_PREFIX: "ModalAddWaybill-ShipmentDetailsTable-StockOrderRow",
    MODAL_ADD_WAYBILL_SHIPMENT_DETAILS_TABLE_STOCK_ORDER_ROW_ORDER_NUMBER_CELL_SUFFIX: "-OrderNumberCell",
    MODAL_ADD_WAYBILL_SHIPMENT_DETAILS_TABLE_STOCK_ORDER_ROW_REMAINING_QUANTITY_CELL_SUFFIX: "-RemainingQuantityCell",
    MODAL_ADD_WAYBILL_CONTROL_BUTTONS_ACTUALIZE_BUTTON: "ModalAddWaybill-ControlButtons-ActualizeButton",
    MODAL_ADD_WAYBILL_SHIPMENT_DETAILS_TABLE_TOTAL_LEFT_TO_DO_LABEL: "ModalAddWaybill-ShipmentDetailsTable-TotalLeftToDoLabel",
    MODAL_ADD_WAYBILL_DETAILS_TABLE_TABLE: "ModalAddWaybill-DetailsTable-Table",
    MODAL_ADD_WAYBILL_DETAILS_TABLE_ROW_NAME_CELL_PREFIX: "ModalAddWaybill-DetailsTable-Row",
    MODAL_ADD_WAYBILL_DETAILS_TABLE_ROW_NAME_CELL_SUFFIX: "-NameCell",
    MODAL_ADD_WAYBILL_DETAILS_TABLE_ROW_QUANTITY_CELL_SUFFIX: "-QuantityCell",
    MODAL_ADD_WAYBILL_DETAILS_TABLE_ROW_IN_KITS_CELL_SUFFIX: "-InKitsCell",
    MODAL_ADD_WAYBILL_DETAILS_TABLE_ROW_FREE_QUANTITY_CELL_SUFFIX: "-FreeQuantityCell",
    MODAL_ADD_WAYBILL_DETAILS_TABLE_ROW_SCLAD_NEED_CELL_SUFFIX: "-ScladNeedCell",
    MODAL_ADD_WAYBILL_DETAILS_TABLE_ROW_NEED_CELL_SUFFIX: "-NeedCell",
    TABLE_COMPLECT_TABLE_COMPLECT_MODAL_ADD_WAYBILL_CIRCLE_PROGRESS_WRAPPER_PREFIX: "TableComplect-ModalAddWaybill",
    TABLE_COMPLECT_TABLE_COMPLECT_MODAL_ADD_WAYBILL_CIRCLE_PROGRESS_WRAPPER_SUFFIX: "-CircleProgress-Wrapper",
    OSTATK_PCBD_MODAL_DETAL_PREFIX: "OstatkPCBD-ModalDetal",
    OSTATK_PCBD_MODAL_DETAL_INFORMATION_NAME_NAME_SUFFIX: "-InformationName-Name",
    OSTATK_PCBD_MODAL_DETAL_BUTTONS_SHOW_FULL_INFORMATION_BUTTON_SUFFIX: "-Buttons-ShowFullInformationButton",
    // Test Data erp-969-2
    DETAIL_1_NAME: "ERP9692_DETAIL_001",
    DETAIL_2_NAME: "ERP9692_DETAIL_002",
    ASSEMBLY_NAME: "ERP9692_ASSEMBLY_001",
    DETAIL_NEW_QUANTITY: "9",
    NEW_ORDER_QUANTITY: "3",
};
